### ISSUE TITLE
安装失败，名字的问题吗？biluanlv？bilulanlv？

### ISSUE THREAD

**Issue by jonket** [bilulanlv/think-cache#1]
![image](https://github.com/bilulanlv/think-cache/assets/10702573/64e335ab-8275-4d90-a48f-216626732527)

**Comment by jonket** [comment]
composer config -g repo.packagist composer https://packagist.org

**Comment by bilulanlv** [comment]
是的，包名搞错了，我已经改过来了，你重新composer
`composer require bilulanlv/think-cache`
